# Generated by Django 5.1.3 on 2025-01-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productproperty',
            old_name='price',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='sell_price',
            field=models.FloatField(default=232),
            preserve_default=False,
        ),
    ]
