# Generated by Django 5.1.3 on 2024-12-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderdetails',
            old_name='product_In_Supplier',
            new_name='product_in_Supplier',
        ),
    ]
