# Generated by Django 5.1.3 on 2024-12-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_productdetailsupplier_categories'),
        ('warehouses', '0005_alter_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetails',
            name='product_in_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='suppliers.inventorysupplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetails',
            name='purchase_order_from_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouses.purchaseorderfromsupplier'),
        ),
    ]
