# Generated by Django 5.1.3 on 2024-12-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_productdetailsupplier_categories'),
        ('warehouses', '0007_rename_purchase_order_from_supplier_purchaseorderdetails_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderfromsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.supplier'),
        ),
    ]
