# Generated by Django 5.1.3 on 2025-01-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_alter_purchaseorderfromsupplier_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderfromsupplier',
            name='is_applied_to_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
