# Generated by Django 5.1.3 on 2025-01-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productrating_options_and_more'),
        ('warehouses', '0009_purchaseorderfromsupplier_is_applied_to_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='date_of_establishment',
            new_name='stablished_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderfromsupplier',
            name='is_apply_to_inventory',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='taskforemployee',
            unique_together={('employee', 'task')},
        ),
    ]
