# Generated by Django 5.1.3 on 2024-12-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_productdetailsupplier_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailsupplier',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='suppliers.categorysupplier'),
        ),
    ]
