# Generated by Django 5.1.3 on 2025-01-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_productdetailsupplier_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysupplier',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='inventorysupplier',
            name='sizes',
        ),
        migrations.AddField(
            model_name='inventorysupplier',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='suppliers.colorsupplier'),
        ),
        migrations.AddField(
            model_name='inventorysupplier',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='suppliers.sizesupplier'),
        ),
    ]
